// Command popular-corpus-gen regenerates the install guard's embedded
// popular-package seeds (core/cli/seeds/npm_popular.txt, pypi_popular.txt)
// from deterministic, download-ranked datasets:
//
//	npm:  wooorm/npm-high-impact — the registry-wide top names ranked by
//	      api.npmjs.org download counts, refreshed monthly upstream.
//	pypi: hugovk/top-pypi-packages — the top PyPI projects ranked by
//	      download counts from the public BigQuery/ClickHouse dataset.
//
// This tool deliberately does NOT use typosquat.Fetcher's live npm path:
// fetchNPM ranks by npm keyword-search popularity (npmSeedKeywords), which is
// non-deterministic between runs and cheap for an attacker to game (keyword
// saturation — see the jose↔jsr denylist note in fetcher.go). A checked-in,
// download-ranked seed reviewed as a data PR is the deterministic channel;
// signed intelligence bundles (content key "typosquat") are the refresh
// channel between releases.
//
// The output line order IS the rank: the guard's parsePopularSeed assigns
// Rank from position, and the typosquat verdict ladder blocks d=1 hits only
// against top-ranked targets. Don't sort or dedupe-reorder the file.
//
// Safety rails: the tool refuses to write a corpus below -floor entries
// (mirrors the fetcher's poisoning floor) or one missing the per-ecosystem
// sentinel names — both indicate an upstream format change, not a real
// shrink of the ecosystem.
//
// Usage (from core/):
//
//	go run ./tools/popular-corpus-gen -ecosystem npm  -limit 5000 -out cli/seeds/npm_popular.txt
//	go run ./tools/popular-corpus-gen -ecosystem pypi -limit 3000 -out cli/seeds/pypi_popular.txt
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"
)

const (
	npmSourceURL  = "https://raw.githubusercontent.com/wooorm/npm-high-impact/main/lib/top.js"
	pypiSourceURL = "https://raw.githubusercontent.com/hugovk/top-pypi-packages/main/top-pypi-packages.min.json"
)

// sentinels are names that MUST appear in a healthy corpus for the
// ecosystem. Absence means the upstream dataset moved or changed shape —
// fail loudly instead of committing a hollow seed.
var sentinels = map[string][]string{
	"npm":  {"react", "typescript", "lodash", "express"},
	"pypi": {"requests", "numpy", "boto3", "urllib3"},
}

func main() {
	eco := flag.String("ecosystem", "", "npm | pypi")
	limit := flag.Int("limit", 5000, "number of top names to keep (rank order)")
	out := flag.String("out", "", "output seed file path")
	src := flag.String("source", "", "override the dataset URL (tests, mirrors)")
	floor := flag.Int("floor", 500, "refuse to write a corpus smaller than this")
	flag.Parse()

	if *eco == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: popular-corpus-gen -ecosystem npm|pypi -out <seed file> [-limit N]")
		os.Exit(2)
	}
	names, sourceURL, err := fetchRanked(*eco, *src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "popular-corpus-gen: %v\n", err)
		os.Exit(1)
	}
	if len(names) > *limit {
		names = names[:*limit]
	}
	if len(names) < *floor {
		fmt.Fprintf(os.Stderr, "popular-corpus-gen: dataset yielded %d names, below the %d floor — upstream format change?\n", len(names), *floor)
		os.Exit(1)
	}
	for _, sentinel := range sentinels[strings.ToLower(*eco)] {
		if !contains(names, sentinel) {
			fmt.Fprintf(os.Stderr, "popular-corpus-gen: sentinel %q missing from the top %d — upstream format change?\n", sentinel, len(names))
			os.Exit(1)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Popular-%s seed for the local-first install guard's offline typosquat corpus.\n", *eco)
	fmt.Fprintf(&b, "# GENERATED by core/tools/popular-corpus-gen — do not hand-edit; regenerate with:\n")
	fmt.Fprintf(&b, "#   go run ./tools/popular-corpus-gen -ecosystem %s -limit %d -out %s\n", *eco, *limit, *out)
	fmt.Fprintf(&b, "# Source: %s (download-ranked)\n", sourceURL)
	fmt.Fprintf(&b, "# Generated: %s | entries: %d\n", time.Now().UTC().Format("2006-01-02"), len(names))
	fmt.Fprintf(&b, "# LINE ORDER IS RANK — the guard's verdict ladder depends on it; do not sort.\n")
	for _, n := range names {
		b.WriteString(n)
		b.WriteByte('\n')
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "popular-corpus-gen: write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "popular-corpus-gen: wrote %d %s names to %s\n", len(names), *eco, *out)
}

func fetchRanked(eco, override string) ([]string, string, error) {
	switch strings.ToLower(eco) {
	case "npm":
		url := npmSourceURL
		if override != "" {
			url = override
		}
		raw, err := httpGet(url)
		if err != nil {
			return nil, url, err
		}
		return parseNPMHighImpact(raw), url, nil
	case "pypi", "pip":
		url := pypiSourceURL
		if override != "" {
			url = override
		}
		raw, err := httpGet(url)
		if err != nil {
			return nil, url, err
		}
		names, err := parseTopPyPI(raw)
		return names, url, err
	default:
		return nil, "", fmt.Errorf("unsupported ecosystem %q (npm | pypi)", eco)
	}
}

func httpGet(url string) ([]byte, error) {
	client := &http.Client{Timeout: 60 * time.Second}
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "chainsaw-popular-corpus-gen")
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 32<<20))
}

// npmNameRE matches the single-quoted package names in npm-high-impact's
// `export const top = ['semver', '@babel/core', …]` ES module.
var npmNameRE = regexp.MustCompile(`'((?:@[a-z0-9][\w.-]*/)?[a-z0-9][\w.-]*)'`)

func parseNPMHighImpact(raw []byte) []string {
	seen := map[string]struct{}{}
	var names []string
	for _, m := range npmNameRE.FindAllSubmatch(raw, -1) {
		n := string(m[1])
		if _, dup := seen[n]; dup {
			continue
		}
		seen[n] = struct{}{}
		names = append(names, n)
	}
	return names
}

// parseTopPyPI decodes hugovk's top-pypi-packages JSON: rows of
// {download_count, project}, already ranked by downloads descending.
func parseTopPyPI(raw []byte) ([]string, error) {
	var doc struct {
		Rows []struct {
			Project string `json:"project"`
		} `json:"rows"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse top-pypi-packages JSON: %w", err)
	}
	seen := map[string]struct{}{}
	var names []string
	for _, r := range doc.Rows {
		n := strings.TrimSpace(r.Project)
		if n == "" {
			continue
		}
		if _, dup := seen[n]; dup {
			continue
		}
		seen[n] = struct{}{}
		names = append(names, n)
	}
	return names, nil
}

func contains(names []string, want string) bool {
	for _, n := range names {
		if n == want {
			return true
		}
	}
	return false
}
