package main

// Output and validation.
//
// build FREEZES; validate re-checks the frozen artefact OFFLINE. The split is
// the point: validation that re-queries the network can pass for reasons that
// have nothing to do with the corpus, and would quietly hide a corpus whose
// evidence no longer supports it.

import (
	"compress/gzip"
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/chain305/chainsaw-core/csvsafe"
)

// Manifest is source-manifest.json: everything needed to argue about how this
// corpus came to exist.
type Manifest struct {
	Seed           string         `json:"seed"`
	GeneratedAt    string         `json:"generated_at"`
	OSSFCommit     string         `json:"ossf_commit"`
	OSSFSkipped    map[string]int `json:"ossf_skipped"`
	PoolMultiplier int            `json:"pool_multiplier"`
	Ecosystems     []string       `json:"ecosystems"`
	Duration       string         `json:"duration"`

	// Sampling is NOT uniform in every ecosystem and saying so here is the
	// difference between a limitation and a misrepresentation.
	SamplingNotes map[string]string `json:"sampling_notes"`
}

// vendorHosts are the security vendors whose presence in evidence.jsonl means
// the corpus was contaminated by vendor knowledge during CONSTRUCTION. This is
// the enforced half of the rule stated in main.go; `validate` fails on a hit.
var vendorHosts = []string{
	"socket.dev", "chain305.com", "snyk.io", "jfrog.com", "sonatype.com",
	"mend.io", "phylum.io", "endorlabs.com", "safedep.io", "debricked.com",
	"fossa.com", "checkmarx.com", "veracode.com",
}

func emit(dir string, rows []Row, excl []Exclusion, ev []Evidence, man Manifest) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	man.SamplingNotes = map[string]string{
		"npm":      "prefix-stratified: replicate.npmjs.com rejects offset pagination (HTTP 400 on skip=), so names are drawn from seeded two-character startkey prefixes, NOT uniformly over the registry",
		"go":       "publication-time-stratified: index.golang.org exposes a chronological feed and no name index, so `since` timestamps are sampled uniformly instead of names",
		"cargo":    "window-sampled: crates.io alphabetical pages at seeded random offsets",
		"nuget":    "window-sampled: azuresearch skip offsets",
		"maven":    "window-sampled: solrsearch start offsets, capped at 200k because deep paging degrades",
		"pypi":     "uniform over the complete /simple/ index",
		"rubygems": "uniform over the complete /names index",
		"composer": "uniform over the complete packages/list.json index; versions resolve through Packagist because deps.dev does not index it",
	}

	// IDs are positional over the SORTED corpus, so the same seed and the
	// same upstream snapshot yield the same id for the same coordinate.
	ids := make([]string, len(rows))
	for i := range rows {
		ids[i] = fmt.Sprintf("PIB%06d", i+1)
	}

	// corpus.tsv — the BLIND half. Deliberately the same six-column layout
	// as scripts/detection-eval/corpus-seed.tsv so build-labelled-corpus.sh,
	// socket-snapshot.py and check-corpus-seed.sh consume it unchanged; a
	// new format would have meant rewriting four working consumers to gain
	// nothing.
	var tsv strings.Builder
	fmt.Fprintf(&tsv, "# Detection-eval corpus. GENERATED by core/tools/corpus-gen — do not hand-edit.\n")
	fmt.Fprintf(&tsv, "# seed=%s ossf=%s generated=%s rows=%d\n", man.Seed, man.OSSFCommit, man.GeneratedAt, len(rows))
	fmt.Fprintf(&tsv, "# Ground truth, strata and confidence live in ground-truth.csv, keyed by the\n")
	fmt.Fprintf(&tsv, "# same coordinate. The label column here is the coarse one the existing\n")
	fmt.Fprintf(&tsv, "# harnesses read; it is NOT the ground truth and it flattens B1's\n")
	fmt.Fprintf(&tsv, "# presumed_benign into benign. Grade against ground-truth.csv.\n")
	// The balance marker tells check-corpus-seed.sh that this file's row mix
	// is set by the strata quotas, not by the hand-curated corpus's
	// recall-heavy shape. Its per-ecosystem benign band cannot apply here:
	// public malicious ground truth is ~93% npm, so Go and Maven are almost
	// entirely benign by construction and npm is not. The guard swaps in a
	// stronger check rather than skipping one -- see check-corpus-seed.sh.
	fmt.Fprintf(&tsv, "# corpus-gen-balance: enforced-by-validate\n")
	fmt.Fprintf(&tsv, "# ecosystem\tname\tversion\tpublished\tlabel\texpected_signals\n")
	for _, r := range rows {
		// NEVER emit an empty field. The consumers read rows with
		// `IFS=$'\t' read`, and tab is an IFS whitespace character, so bash
		// COLLAPSES consecutive tabs: an empty field vanishes and every
		// later column shifts left. That defect corrupted 584 of 3,915
		// rows in ingest-ossf.sh on 2026-09-13 and errored nowhere --
		// `published` ended up holding a sha256 and the label column held a
		// date. A few coordinates genuinely have no publication date
		// (Packagist entries with an unparseable time, OpenSSF records with
		// none), so they are written as "-", which is the sentinel
		// check-corpus-seed.sh already accepts.
		published := r.Published
		if strings.TrimSpace(published) == "" {
			published = "-"
		}
		fmt.Fprintf(&tsv, "%s\t%s\t%s\t%s\t%s\t%s\n",
			r.Eco, r.Name, r.Version, published, r.Label, r.Stratum)
	}
	if err := os.WriteFile(filepath.Join(dir, "corpus.tsv"), []byte(tsv.String()), 0o644); err != nil {
		return err
	}

	// ground-truth.csv — the SIGHTED half, kept separate so a collection run
	// can be handed the coordinates without the answers.
	gt, err := os.Create(filepath.Join(dir, "ground-truth.csv"))
	if err != nil {
		return err
	}
	gw := csv.NewWriter(gt)
	_ = gw.Write([]string{"id", "ecosystem", "package", "version", "stratum", "truth",
		"confidence", "pair_id", "licenses", "behaviors", "provenance", "notes"})
	for i, r := range rows {
		_ = gw.Write(csvsafe.Row([]string{ids[i], r.Eco, r.Name, r.Version, r.Stratum, r.Truth,
			r.Confidence, r.PairID, strings.Join(r.Licenses, "|"),
			behaviorString(r.Behaviors), r.Provenance, r.Notes}))
	}
	gw.Flush()
	gt.Close()

	// exclusions.csv — why a candidate did NOT make it. Selection bias is
	// auditable only if the rejections are visible too.
	ex, err := os.Create(filepath.Join(dir, "exclusions.csv"))
	if err != nil {
		return err
	}
	ew := csv.NewWriter(ex)
	_ = ew.Write([]string{"ecosystem", "package", "version", "stratum", "reason"})
	for _, e := range excl {
		_ = ew.Write(csvsafe.Row([]string{e.Eco, e.Name, e.Version, e.Stratum, e.Reason}))
	}
	ew.Flush()
	ex.Close()

	evf, err := os.Create(filepath.Join(dir, "evidence.jsonl"))
	if err != nil {
		return err
	}
	enc := json.NewEncoder(evf)
	for _, e := range ev {
		_ = enc.Encode(e)
	}
	evf.Close()

	stats := buildStats(rows, excl)
	if err := writeJSON(filepath.Join(dir, "statistics.json"), stats); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(dir, "source-manifest.json"), man); err != nil {
		return err
	}

	// SHA256SUMS last: it covers everything above.
	var sums strings.Builder
	names := []string{"corpus.tsv", "ground-truth.csv", "exclusions.csv",
		"evidence.jsonl", "statistics.json", "source-manifest.json"}
	for _, n := range names {
		b, err := os.ReadFile(filepath.Join(dir, n))
		if err != nil {
			return err
		}
		fmt.Fprintf(&sums, "%s  %s\n", sha256Hex(b), n)
	}
	if err := os.WriteFile(filepath.Join(dir, "SHA256SUMS"), []byte(sums.String()), 0o644); err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "\nwrote %d coordinates to %s\n", len(rows), dir)
	for _, q := range quotas {
		n := stats.ByStratum[q.Stratum]
		flag := ""
		if n < q.Target {
			flag = fmt.Sprintf("  (target %d, SHORTFALL %d)", q.Target, q.Target-n)
		}
		fmt.Fprintf(os.Stderr, "  %-4s %5d%s\n", q.Stratum, n, flag)
	}
	fmt.Fprintf(os.Stderr, "\nNext: corpus-gen validate %s\n", dir)
	return nil
}

type Stats struct {
	Total        int            `json:"total"`
	ByStratum    map[string]int `json:"by_stratum"`
	ByEcosystem  map[string]int `json:"by_ecosystem"`
	ByTruth      map[string]int `json:"by_truth"`
	ByConfidence map[string]int `json:"by_confidence"`
	VulnPairs    int            `json:"vuln_pairs"`
	Exclusions   map[string]int `json:"exclusions"`
	// StratumEcosystemSkew records, per stratum, the share held by its
	// largest ecosystem. It exists so a stratum that is 93% one ecosystem
	// cannot be quoted as a cross-ecosystem result without the number
	// sitting right next to it.
	StratumEcosystemSkew map[string]string `json:"stratum_ecosystem_skew"`
}

func buildStats(rows []Row, excl []Exclusion) Stats {
	s := Stats{
		Total: len(rows), ByStratum: map[string]int{}, ByEcosystem: map[string]int{},
		ByTruth: map[string]int{}, ByConfidence: map[string]int{},
		Exclusions: map[string]int{}, StratumEcosystemSkew: map[string]string{},
	}
	perStratumEco := map[string]map[string]int{}
	pairs := map[string]int{}
	for _, r := range rows {
		s.ByStratum[r.Stratum]++
		s.ByEcosystem[r.Eco]++
		s.ByTruth[r.Truth]++
		s.ByConfidence[r.Confidence]++
		if r.PairID != "" {
			pairs[r.PairID]++
		}
		if perStratumEco[r.Stratum] == nil {
			perStratumEco[r.Stratum] = map[string]int{}
		}
		perStratumEco[r.Stratum][r.Eco]++
	}
	for p, n := range pairs {
		if n == 2 {
			s.VulnPairs++
		} else {
			s.Exclusions["incomplete_pair:"+p]++
		}
	}
	for _, e := range excl {
		r := e.Reason
		if i := strings.IndexByte(r, ' '); i > 0 {
			r = r[:i]
		}
		s.Exclusions[r]++
	}
	for st, m := range perStratumEco {
		top, topN, tot := "", 0, 0
		for e, n := range m {
			tot += n
			if n > topN || (n == topN && e < top) {
				top, topN = e, n
			}
		}
		if tot > 0 {
			s.StratumEcosystemSkew[st] = fmt.Sprintf("%s %d/%d (%.0f%%)", top, topN, tot, 100*float64(topN)/float64(tot))
		}
	}
	return s
}

func behaviorString(b Behaviors) string {
	if len(b) == 0 {
		return ""
	}
	keys := make([]string, 0, len(b))
	for k, v := range b {
		if v {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return strings.Join(keys, "|")
}

func writeJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// ─── VALIDATE ───────────────────────────────────────────────────────────────

func cmdValidate(args []string) int {
	fs := flag.NewFlagSet("validate", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if fs.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "DID NOT RUN: usage: corpus-gen validate <dir>")
		return 2
	}
	dir := fs.Arg(0)

	var fail []string
	check := func(cond bool, msg string) {
		if !cond {
			fail = append(fail, msg)
		}
	}

	// A missing file is DID NOT RUN (exit 2), never a pass and never a
	// failure: we could not reach a verdict. Distinguishing the two is the
	// whole convention (CLAUDE.md, "a guard that cannot run is not a guard").
	//
	// evidence.jsonl is the one file large enough that a checked-in corpus
	// will often store it gzipped, so a ".gz" sibling is accepted and
	// transparently decompressed. It is NOT optional: falling through to
	// "no evidence file, nothing to check" would silently disable the
	// contamination guard, which is the single assertion that makes this a
	// benchmark rather than a demo.
	read := func(n string) []byte {
		b, err := os.ReadFile(filepath.Join(dir, n))
		if err == nil {
			return b
		}
		gzPath := filepath.Join(dir, n+".gz")
		if f, gzErr := os.Open(gzPath); gzErr == nil {
			defer f.Close()
			zr, zErr := gzip.NewReader(f)
			if zErr == nil {
				defer zr.Close()
				if out, rErr := io.ReadAll(zr); rErr == nil {
					return out
				}
			}
			fmt.Fprintf(os.Stderr, "DID NOT RUN: %s.gz is unreadable\n", n)
			os.Exit(2)
		}
		fmt.Fprintf(os.Stderr, "DID NOT RUN: %s: %v\n", n, err)
		os.Exit(2)
		return nil
	}

	sums := read("SHA256SUMS")
	for _, ln := range strings.Split(strings.TrimSpace(string(sums)), "\n") {
		f := strings.Fields(ln)
		if len(f) != 2 {
			continue
		}
		got := sha256Hex(read(f[1]))
		check(got == f[0], fmt.Sprintf("%s: sha256 %s, SHA256SUMS says %s", f[1], got[:12], f[0][:12]))
	}

	// corpus.tsv
	type co struct{ eco, name, ver, label, stratum string }
	var coords []co
	seen := map[string]bool{}
	for _, ln := range strings.Split(string(read("corpus.tsv")), "\n") {
		if ln == "" || strings.HasPrefix(ln, "#") {
			continue
		}
		f := strings.Split(ln, "\t")
		if len(f) < 6 {
			fail = append(fail, "corpus.tsv: short row: "+ln)
			continue
		}
		c := co{f[0], f[1], f[2], f[4], f[5]}
		check(c.ver != "" && c.ver != "*", "corpus.tsv: non-exact version: "+ln)
		k := c.eco + "\x00" + c.name + "\x00" + c.ver
		check(!seen[k], "corpus.tsv: duplicate coordinate: "+k)
		seen[k] = true
		coords = append(coords, c)
	}

	// ground-truth.csv, and its agreement with corpus.tsv
	gtr := csv.NewReader(strings.NewReader(string(read("ground-truth.csv"))))
	recs, err := gtr.ReadAll()
	if err != nil {
		fmt.Fprintf(os.Stderr, "DID NOT RUN: ground-truth.csv: %v\n", err)
		return 2
	}
	check(len(recs) > 1, "ground-truth.csv is empty")
	check(len(recs)-1 == len(coords),
		fmt.Sprintf("ground-truth.csv has %d rows, corpus.tsv has %d", len(recs)-1, len(coords)))
	pairs := map[string][]string{}
	ids := map[string]bool{}
	for _, r := range recs[1:] {
		if len(r) < 8 {
			fail = append(fail, "ground-truth.csv: short row")
			continue
		}
		id, eco, name, ver, stratum, truth, conf, pair := unescapeCell(r[0]), unescapeCell(r[1]),
			unescapeCell(r[2]), unescapeCell(r[3]), unescapeCell(r[4]), unescapeCell(r[5]),
			unescapeCell(r[6]), unescapeCell(r[7])
		check(!ids[id], "duplicate id "+id)
		ids[id] = true
		check(seen[eco+"\x00"+name+"\x00"+ver], "ground-truth row absent from corpus.tsv: "+id)
		check(truth != "benign", id+": truth is 'benign'; no upstream proves benignity — use presumed_benign")
		check(conf == "A" || conf == "B" || conf == "C", id+": confidence must be A, B or C, got "+conf)
		if pair != "" {
			pairs[pair] = append(pairs[pair], stratum+":"+eco+"/"+name)
		}
	}
	for p, members := range pairs {
		check(len(members) == 2, fmt.Sprintf("pair %s has %d members, want 2 (a vulnerable version and its fixed control)", p, len(members)))
		if len(members) == 2 {
			a := strings.SplitN(members[0], ":", 2)[1]
			b := strings.SplitN(members[1], ":", 2)[1]
			check(a == b, fmt.Sprintf("pair %s spans two packages (%s, %s); the control must be the SAME package", p, a, b))
		}
	}

	// The contamination guard. This is the assertion that makes the corpus a
	// benchmark rather than a demo, so it is enforced, not documented.
	for _, ln := range strings.Split(string(read("evidence.jsonl")), "\n") {
		if strings.TrimSpace(ln) == "" {
			continue
		}
		low := strings.ToLower(ln)
		for _, h := range vendorHosts {
			if strings.Contains(low, h) {
				fail = append(fail, "evidence.jsonl references a security vendor ("+h+"): the corpus was contaminated during construction")
				break
			}
		}
	}

	var st Stats
	if err := json.Unmarshal(read("statistics.json"), &st); err != nil {
		fmt.Fprintf(os.Stderr, "DID NOT RUN: statistics.json: %v\n", err)
		return 2
	}
	check(st.Total == len(coords), "statistics.json total disagrees with corpus.tsv")

	var man Manifest
	if err := json.Unmarshal(read("source-manifest.json"), &man); err != nil {
		fmt.Fprintf(os.Stderr, "DID NOT RUN: source-manifest.json: %v\n", err)
		return 2
	}
	check(man.Seed != "", "source-manifest.json: no seed recorded")
	check(len(man.OSSFCommit) == 40, "source-manifest.json: OpenSSF commit not pinned to a full sha")

	fmt.Printf("corpus:      %s\n", dir)
	fmt.Printf("coordinates: %d\n", len(coords))
	fmt.Printf("seed:        %s\n", man.Seed)
	fmt.Printf("ossf:        %s\n", man.OSSFCommit)
	fmt.Printf("vuln pairs:  %d\n", st.VulnPairs)
	strata := make([]string, 0, len(st.ByStratum))
	for k := range st.ByStratum {
		strata = append(strata, k)
	}
	sort.Strings(strata)
	for _, k := range strata {
		fmt.Printf("  %-4s %5d   skew %s\n", k, st.ByStratum[k], st.StratumEcosystemSkew[k])
	}
	if len(fail) > 0 {
		fmt.Fprintf(os.Stderr, "\nFAIL: %d problems\n", len(fail))
		for i, f := range fail {
			if i == 40 {
				fmt.Fprintf(os.Stderr, "  ... and %d more\n", len(fail)-40)
				break
			}
			fmt.Fprintln(os.Stderr, "  "+f)
		}
		return 1
	}
	fmt.Println("\nOK")
	return 0
}

// unescapeCell inverts csvsafe.Field for the read-back in validate.
//
// ground-truth.csv is written through csvsafe.Row, so any cell whose value
// begins `= + - @` TAB or CR carries a leading apostrophe. Scoped npm names
// are the common case, not the exotic one: `@babel/core` is escaped like any
// other formula-shaped value, and validate cross-checks the coordinate
// columns against corpus.tsv, which is a TSV and is NOT escaped. Comparing
// the two without stripping would fail every scoped package in the corpus
// while reporting it as a corpus defect.
func unescapeCell(v string) string { return strings.TrimPrefix(v, "'") }
