package cli

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseCargoInstall(t *testing.T) {
	// Non-install subcommand → not recognized.
	if specs, ok := parseCargoInstall([]string{"build", "--release"}); ok || specs != nil {
		t.Fatalf("cargo build should not be recognized as install; got %v ok=%v", specs, ok)
	}

	// `cargo add serde`.
	specs, ok := parseCargoInstall([]string{"add", "serde"})
	if !ok || len(specs) != 1 {
		t.Fatalf("cargo add serde: ok=%v specs=%v", ok, specs)
	}
	if specs[0].Ecosystem != "cargo" || specs[0].Name != "serde" || specs[0].Version != "" {
		t.Fatalf("cargo add serde wrong spec: %+v", specs[0])
	}

	// `cargo install ripgrep`.
	specs, ok = parseCargoInstall([]string{"install", "ripgrep"})
	if !ok || len(specs) != 1 || specs[0].Name != "ripgrep" || specs[0].Ecosystem != "cargo" {
		t.Fatalf("cargo install ripgrep: ok=%v specs=%v", ok, specs)
	}

	// name@version form.
	specs, _ = parseCargoInstall([]string{"add", "serde@1.0.0"})
	if len(specs) != 1 || specs[0].Name != "serde" || specs[0].Version != "1.0.0" {
		t.Fatalf("cargo add serde@1.0.0 wrong spec: %+v", specs)
	}

	// --version X form consumes its value and pins the prior crate.
	specs, _ = parseCargoInstall([]string{"install", "ripgrep", "--version", "13.0.0"})
	if len(specs) != 1 || specs[0].Name != "ripgrep" || specs[0].Version != "13.0.0" {
		t.Fatalf("cargo install --version wrong spec: %+v", specs)
	}

	// Bare `cargo add` (no crate) is recognized with no specs → triggers lockfile scan.
	if specs, ok := parseCargoInstall([]string{"add"}); !ok || len(specs) != 0 {
		t.Fatalf("bare cargo add: ok=%v specs=%v (want ok=true, 0 specs)", ok, specs)
	}
}

func TestParseGemInstall(t *testing.T) {
	if specs, ok := parseGemInstall([]string{"list"}); ok || specs != nil {
		t.Fatalf("gem list should not be recognized as install; got %v ok=%v", specs, ok)
	}

	// `gem install rails`.
	specs, ok := parseGemInstall([]string{"install", "rails"})
	if !ok || len(specs) != 1 {
		t.Fatalf("gem install rails: ok=%v specs=%v", ok, specs)
	}
	if specs[0].Ecosystem != "rubygems" || specs[0].Name != "rails" || specs[0].Version != "" {
		t.Fatalf("gem install rails wrong spec: %+v", specs[0])
	}

	// `-v X` pins the version.
	specs, _ = parseGemInstall([]string{"install", "rails", "-v", "7.1.0"})
	if len(specs) != 1 || specs[0].Name != "rails" || specs[0].Version != "7.1.0" {
		t.Fatalf("gem install rails -v 7.1.0 wrong spec: %+v", specs)
	}

	// name:version form.
	specs, _ = parseGemInstall([]string{"install", "rails:7.1.0"})
	if len(specs) != 1 || specs[0].Name != "rails" || specs[0].Version != "7.1.0" {
		t.Fatalf("gem install rails:7.1.0 wrong spec: %+v", specs)
	}
}

func TestParseCargoLock(t *testing.T) {
	fixture := `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "ripgrep"
version = "13.0.0"
dependencies = [
 "serde",
]
`
	deps := parseCargoLock([]byte(fixture))
	if len(deps) != 2 {
		t.Fatalf("expected 2 packages, got %d: %v", len(deps), deps)
	}
	if deps["serde"] != "1.0.197" {
		t.Errorf("serde version = %q, want 1.0.197", deps["serde"])
	}
	if deps["ripgrep"] != "13.0.0" {
		t.Errorf("ripgrep version = %q, want 13.0.0", deps["ripgrep"])
	}
}

func TestExpandLockfileCargoAndRubygems(t *testing.T) {
	dir := t.TempDir()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(cwd) })

	cargoLock := `[[package]]
name = "serde"
version = "1.0.197"

[[package]]
name = "anyhow"
version = "1.0.86"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.lock"), []byte(cargoLock), 0o644); err != nil {
		t.Fatal(err)
	}

	specs := expandLockfile("cargo", []string{"build"})
	if len(specs) != 2 {
		t.Fatalf("cargo expandLockfile: got %d specs, want 2: %v", len(specs), specs)
	}
	for _, s := range specs {
		if s.Ecosystem != "cargo" {
			t.Errorf("cargo spec has wrong ecosystem: %+v", s)
		}
	}

	gemfileLock := `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.1.0)
    rake (13.0.6)

PLATFORMS
  ruby
`
	if err := os.WriteFile(filepath.Join(dir, "Gemfile.lock"), []byte(gemfileLock), 0o644); err != nil {
		t.Fatal(err)
	}

	specs = expandLockfile("gem", []string{"install"})
	if len(specs) != 2 {
		t.Fatalf("gem expandLockfile: got %d specs, want 2: %v", len(specs), specs)
	}
	for _, s := range specs {
		if s.Ecosystem != "rubygems" {
			t.Errorf("gem spec has wrong ecosystem: %+v", s)
		}
	}
}
