package codesmell

import "testing"

func TestIsLikelyTestOrVendor(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		// Kept (real source).
		{"src/foo.js", false},
		{"lib/index.ts", false},
		{"package/main.py", false},
		{"app/server.go", false},
		// Vendored.
		{"node_modules/lodash/index.js", true},
		{"some/pkg/node_modules/x/y.js", true},
		{"vendor/github.com/foo/bar.go", true},
		{"python/site-packages/requests/api.py", true},
		{"proj/__pycache__/mod.cpython-310.pyc", true},
		// Tests.
		{"__tests__/bar.test.js", true},
		{"src/foo_test.go", true},
		{"app/foo.spec.ts", true},
		{"test/helper.js", true},
		{"tests/integration/x.py", true},
		{"spec/models/user_spec.rb", true},
		{"pkg/testdata/golden.json", true},
		{"app/fixtures/payload.json", true},
		// Build / dist.
		{"dist/bundle.js", true},
		{"build/output.js", true},
		{"web/.next/static/chunks/main.js", true},
		{"target/release/foo", true},
		// Examples / docs.
		{"examples/demo.js", true},
		{"docs/intro.md", true},
		// Go module zips: the module PATH is a name, not a directory.
		{"vitess.io/vitess/examples/are-you-alive@v0.0.0-20201226175325-4df037de0a7d/pkg/client/client.go", false},
		{"k8s.io/kops/tests/e2e@v0.0.0-20260505071424-48f41f4149cd/pkg/env.go", false},
		{"k8s.io/kops/tests/e2e@v0.0.0-20260505071424-48f41f4149cd/test/fake.go", true},
		{"node_modules/@vue/shared/dist/shared.js", true},
		// Case-insensitive + backslash normalisation.
		{"Node_Modules/x.js", true},
		{`pkg\__tests__\bar.test.js`, true},
		// Edge: empty.
		{"", false},
		// Edge: substring of a segment is NOT enough — must match boundaries.
		{"src/contest/foo.js", false},
		{"src/manifesto/foo.js", false},
		// Go ignores _ and . directories and files; other languages do not.
		{"github.com/stretchr/testify@v1.12.1/_readme-gofmt/main.go", true},
		{"mod@v1.0.0/.github/gen/main.go", true},
		{"mod@v1.0.0/internal/_gen.go", true},
		{"mod@v1.0.0/internal/run.go", false},
		{"pkg/_internal/run.py", false},
	}
	for _, tc := range cases {
		got := IsLikelyTestOrVendor(tc.path)
		if got != tc.want {
			t.Errorf("IsLikelyTestOrVendor(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestIsLikelyI18nFile(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		// i18n directories.
		{"package/locales/ar.json", true},
		{"package/locale/en/messages.json", true},
		{"src/i18n/strings.yaml", true},
		{"app/lang/de.yml", true},
		{"pkg/translations/fr.json", true},
		{"src/messages/intro.md", true},
		// Translation catalog extensions.
		{"foo/bar/ar.po", true},
		{"foo/bar/template.pot", true},
		{"foo/bar/compiled.mo", true},
		{"app/locales/de.ftl", true},
		{"resources/en.lproj/Localizable.strings", true},
		{"app/values-ar/strings.xml", true},
		// Conventional filenames anywhere.
		{"public/messages.json", true},
		// Non-i18n.
		{"src/main.js", false},
		{"src/foo.json", false},
		{"package/index.ts", false},
		{"", false},
	}
	for _, tc := range cases {
		if got := IsLikelyI18nFile(tc.path); got != tc.want {
			t.Errorf("IsLikelyI18nFile(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestLooksGenerated(t *testing.T) {
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"plain", "function foo() { return 1; }", false},
		{"at-generated", "// @generated by protoc\nfoo()\n", true},
		{"auto-generated-c", "/* AUTO-GENERATED FILE - do not edit */\n", true},
		{"hash-generated", "# Generated by Cargo\n[package]\n", true},
		{"html-generated", "<!-- Generated by docgen -->\n<html/>\n", true},
		{"empty", "", false},
		{"marker beyond probe", largeHead("// @generated", 1000), false},
		{"marker within probe", largeHead("// @generated", 100), true},
	}
	for _, tc := range cases {
		got := LooksGenerated([]byte(tc.body))
		if got != tc.want {
			t.Errorf("%s: LooksGenerated = %v, want %v", tc.name, got, tc.want)
		}
	}
}

// largeHead returns padding + marker, where padding is `pad` bytes of spaces
// followed by the marker. Used to verify we only inspect the head probe.
func largeHead(marker string, pad int) string {
	b := make([]byte, pad)
	for i := range b {
		b[i] = ' '
	}
	return string(b) + marker
}

func TestFilterTestVendorGenerated(t *testing.T) {
	in := map[string][]byte{
		"src/foo.js":                []byte("module.exports = 1\n"),
		"node_modules/x/index.js":   []byte("module.exports = 2\n"),
		"__tests__/bar.test.js":     []byte("test('x', () => {})\n"),
		"dist/bundle.js":            []byte("var a=1;a;"),
		"src/generated/proto.pb.go": []byte("// @generated by protoc\npackage gen\n"),
		"src/keep.go":               []byte("package keep\n"),
	}
	out := FilterTestVendorGenerated(in)

	mustHave := []string{"src/foo.js", "src/keep.go"}
	mustDrop := []string{
		"node_modules/x/index.js",
		"__tests__/bar.test.js",
		"dist/bundle.js",
		"src/generated/proto.pb.go",
	}
	for _, p := range mustHave {
		if _, ok := out[p]; !ok {
			t.Errorf("expected %q to be kept", p)
		}
	}
	for _, p := range mustDrop {
		if _, ok := out[p]; ok {
			t.Errorf("expected %q to be dropped", p)
		}
	}

	// Sanity: nil/empty input passes through.
	if got := FilterTestVendorGenerated(nil); got != nil {
		t.Errorf("nil input should pass through, got %v", got)
	}
}

// TestFilterAllowsMinifiedAndNativeTargets documents the contract that
// MinifiedCode and NativeBinary scanners must NOT use this filter — so we
// verify here that the would-be-excluded paths really are excluded by it
// (the scanner call sites are responsible for opting out).
func TestFilterAllowsMinifiedAndNativeTargets(t *testing.T) {
	// dist/bundle.js is the canonical minified target; vendor/lib.so is the
	// canonical native-binary-in-vendor target. Both are dropped by the
	// filter — which is why call sites for ScanMinified and ScanNativeBinary
	// must not apply it.
	if !IsLikelyTestOrVendor("dist/bundle.js") {
		t.Error("dist/bundle.js should be filtered (and so MinifiedCode must opt out)")
	}
	if !IsLikelyTestOrVendor("vendor/foo/lib.so") {
		t.Error("vendor/foo/lib.so should be filtered (and so NativeBinary must opt out)")
	}
}

// npm's published code is usually dist/ or build/. The URL scanner keeps it;
// the capability axes do not (see FilterTestVendorGeneratedKeepBuild).
func TestFilterKeepBuildKeepsPackageBuildOutput(t *testing.T) {
	in := map[string][]byte{
		"package/dist/api-operations/authorize-account.js": []byte("x"),
		"package/build/config/constants.js":                []byte("x"),
		"package/test/fixture.js":                          []byte("x"),
		"package/node_modules/dep/dist/index.js":           []byte("x"),
	}
	got := FilterTestVendorGeneratedKeepBuild(in)
	for _, p := range []string{"package/dist/api-operations/authorize-account.js", "package/build/config/constants.js"} {
		if _, ok := got[p]; !ok {
			t.Errorf("build output %s was filtered", p)
		}
	}
	for _, p := range []string{"package/test/fixture.js", "package/node_modules/dep/dist/index.js"} {
		if _, ok := got[p]; ok {
			t.Errorf("%s survived the filter", p)
		}
	}
	if _, ok := FilterTestVendorGenerated(in)["package/dist/api-operations/authorize-account.js"]; ok {
		t.Error("the default filter must still drop dist/")
	}
}
