package intelligence

import (
	"context"
	"strings"
)

// normalizeEcosystemKey is the single spelling every provider's
// `Supports` whitelist lookup must use.
//
// Key.Ecosystem is never normalised by the caller: it arrives verbatim
// from a URL path segment (`/api/v1/intel/packages/PyPI/...`), a
// lockfile parser, a policy row or a proxy repository config. Half the
// providers lower-cased on the way in and half compared the raw string,
// so a `PyPI`-cased coordinate kept its OSV and registry-metadata lanes
// and silently lost its CVE, typosquat, malware and checksum lanes —
// and the skip at scanner.go's `if !p.Supports(...) { continue }` emits
// nothing, so the loss is invisible in the Report. P8-33.
//
// This is a lookup-key normaliser, NOT an alias resolver: `pypi`→`pip`
// and friends stay the business of each provider's own whitelist (which
// carries both spellings) and of malware.NormalizeEcosystem.
func normalizeEcosystemKey(ecosystem string) string {
	return strings.ToLower(strings.TrimSpace(ecosystem))
}

// Provider contributes a slice of the Report. Providers are pure relative
// to the Request — they do not mutate each other; the Scan orchestrator is
// responsible for merging PartialReport values.
type Provider interface {
	// Name is a stable identifier — used as the warning.provider tag,
	// the singleflight key suffix, and the observability timing label.
	Name() string

	// Signal is the bit in SignalMask that selects this provider.
	Signal() SignalMask

	// NeedsArtifact reports whether the provider can run without an
	// ArtifactHandle. Tier-2 providers (install scripts, hidden unicode)
	// return true; Tier-1 providers return false.
	NeedsArtifact() bool

	// Tier is the ordering bucket this provider belongs to. The Scan
	// pipeline runs all Tier-1 + Tier-2 providers in parallel, waits
	// for the merge, then runs Tier-3 providers with the merged Report
	// accessible through the `prior` argument.
	//   1 — independent fetches (metadata-only)
	//   2 — artifact-bound fetches (install scripts, hidden unicode)
	//   3 — derived signals that depend on the merged Report
	Tier() int

	// Supports decides whether this provider has anything to say about
	// the given ecosystem. Providers that return false are skipped
	// silently — the matrix cell is ❌ by design, not a warning.
	Supports(ecosystem string) bool

	// Run contributes a partial slice to the Report. Must be idempotent
	// and must never panic — returning (PartialReport{}, err) is the
	// correct failure mode; err becomes a Warning.
	Run(ctx context.Context, req Request, prior *Report) (PartialReport, error)
}

// PartialReport is the output shape of a single provider. The Scan
// orchestrator merges these into the final Report. Zero-valued fields are
// left untouched in the merge — providers only set what they produced.
type PartialReport struct {
	Release     *ReleaseSection
	URLs        *URLSection
	Artifact    *ArtifactSection
	People      *PeopleSection
	Metadata    *MetadataSection
	Provenance  *ProvenanceSection
	Scan        *ArtifactScanSection
	SupplyChain *SupplyChainSection
	Vulns       *VulnSection
	Maintenance *MaintenanceSection
	// Dependencies is the manifest-declared dependency list extracted
	// from the upstream registry. Populated by registrymetadata for
	// ecosystems whose packument carries it (npm, PyPI, cargo, etc.).
	Dependencies *DependenciesSection
	// Warnings generated by this provider, appended to Observation.Warnings.
	Warnings []Warning
}
